#!/usr/bin/env bash


# Highlight section titles in manual pages.
export LESS_TERMCAP_md="${yellow}";

# Don’t clear the screen after quitting a manual page.
export MANPAGER='less -X';

# Always enable colored `grep` output.
export GREP_OPTIONS='--color=auto';

# Python Virtual Environments
export WORKON_HOME=$HOME/.virtualenvs;

# Fix `Inappropriate ioctl for device` gpg error.
# @see https://github.com/keybase/keybase-issues/issues/1712
export GPG_TTY=$(tty)
