#!/usr/bin/env bash


# Add Homebrew's sbin to PATH.
export PATH="/usr/local/sbin:$PATH"

# Add nvm to PATH.
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
