#!/usr/bin/env bash

step "Adding configuration files…"

if [[ ! $(cat ~/.gnupg/gpg-agent.conf | grep "pinentry-program") ]]; then
	echo_install "Configuring gpg-agent"
	echo "pinentry-program (which pinentry-mac)\n" >> ~/.gnupg/gpg-agent.conf
	print_in_green "${bold}✓ done!${normal}\n"
else
	print_success_muted "gpg-agent already configured. Skipped."
fi
